### ISSUE TITLE
[ErrorException] chdir(): Permission denied (errno 13)

### ISSUE THREAD

**Issue by mrmad** [VirtuBox/ubuntu-nginx-web-server#1]
I receive an error after this command:
`sudo -u www-data composer update -d /var/www/22222/htdocs/db/pma/`

> Cannot create cache directory /root/.composer/cache/repo/https---www.phpmyadmin.net/, or directory is not writable. Proceeding without cache
Cannot create cache directory /root/.composer/cache/repo/https---packagist.org/, or directory is not writable. Proceeding without cache
Cannot create cache directory /root/.composer/cache/files/, or directory is not writable. Proceeding without cache
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Generating autoload files

                                         
  [ErrorException]                       
  chdir(): Permission denied (errno 13)

**Comment by VirtuBox** [comment]
Hello,
I have noticed this error too, but it doesn't seems to affect phpmyadmin package update.

**Comment by robwilde** [comment]
If you add the folders and set them as 777, you will be able to configure the cache for .composer

**Comment by VirtuBox** [comment]
No need to set permissions to 777, it's only because folder /var/www owner is root, not www-data.
