### ISSUE TITLE
this option doesn't exist issue.

### ISSUE THREAD

**Issue by niteshmanav** [VirtuBox/ubuntu-nginx-web-server#13]
Thank you for the wonderful script. Sadly I am facing an issue currently. 

Kindly have a look at this screenshot: http://url.digitallyup.stream/t0de

After running the following script for SSL installation using ACME:
`cd && bash <(wget --no-check-certificate -O - https://raw.githubusercontent.com/VirtuBox/ee-acme-sh/master/install.sh)
# enable acme.sh & ee-acme-sh
source .bashrc`

It asked to select which mode of validation I want but no matter what option I choose, it always gives an error which says "this option doesn't exist". Tried multiple times and multiple variations. Nothing worked. 

Please help me with this. 

Thanks.

**Comment by VirtuBox** [comment]
Hello @niteshmanav, 

I have updated my script to fix this issue, This time it will ask you another time what option you want to choose instead of exiting the script.
But you may have to check the content of the file .acme.sh/account.conf and to remove lines with empty variables like : 
```
SAVED_CF_Key=''
SAVED_CF_Email=''
```
