### ISSUE TITLE
Fail2Ban

### ISSUE THREAD

**Issue by wiroy** [VirtuBox/ubuntu-nginx-web-server#14]
root@ip-172-31-35-69:/etc/nginx/common# fail2ban-client reload
ERROR  Found no accessible config files for 'filter.d/nginx-forbidden' under /etc/fail2ban
ERROR  No section: 'Definition'
ERROR  No section: 'Definition'
ERROR  Unable to read the filter
ERROR  Errors in jail 'nginx-forbidden'. Skipping...

**Comment by VirtuBox** [comment]
Hello @wiroy,

To fix this issue, you just need to download the missing filter : 
```
wget -O /etc/fail2ban/filter.d/nginx-forbidden.conf https://virtubox.github.io/ubuntu-nginx-web-server/files/etc/fail2ban/filter.d/nginx-forbidden.conf
```
And then to run `fail2ban-client reload` again.
I will add this missing line asap
