### ISSUE TITLE
Nginx Port Change Error

### ISSUE THREAD

**Issue by wiroy** [VirtuBox/ubuntu-nginx-web-server#15]
Hello @VirtuBox 

Ubuntu nginx web server server to my varnish cache installation and varnishe 80 port, and I change the port of nginx 8080, but although I do not change the port nginx 80 is running. I would like to help you resolve the problem on easyengine varnish how to install and optimization can do.

**Comment by wiroy** [comment]
Hello

Do you assign the location of the config files to change the port

**Comment by VirtuBox** [comment]
Hello,

what do you mean ?

**Comment by wiroy** [comment]
Hello

Nginx port change but not search file.

**Comment by VirtuBox** [comment]
Hello,
you can find all configuration files with the directive `listen 80;` with the following command : 

```bash
grep "listen 80;" -r /etc/nginx
```
