### ISSUE TITLE
webp_suffix is not defined

### ISSUE THREAD

**Issue by BenKnigge** [VirtuBox/ubuntu-nginx-web-server#16]
the variable webp_suffix is being used in the following files

/etc/nginx/common/wpcommon-php71.conf
/etc/nginx/common/wpcommon-php72.conf
/etc/nginx/common/wpcommon-php7.conf

However it has not been defined and results in the following error when running the command :

nginx -t

nginx: [emerg] unknown "webp_suffix" variable

**Comment by VirtuBox** [comment]
Hello,

you need to download the webp mapping configuration : 

```bash
wget -O /etc/nginx/conf.d/webp.conf  https://virtubox.github.io/ubuntu-nginx-web-server/files/etc/nginx/conf.d/webp.conf
```

I will reorder installation steps soon to avoid this issue
