### ISSUE TITLE
Will this work with EEv4 

### ISSUE THREAD

**Issue by ashishdungdung** [VirtuBox/ubuntu-nginx-web-server#18]
Greetings, I have been also fan of your work, thanks for contributing so much, just had a query, that will this  git work with the latest EE v4.0. It was just released today or will this need additional modifications based on the new structure of EE v4.

**Comment by VirtuBox** [comment]
Hello @ashishdungdung, 
at the moment I haven't use EEv4 to be able to say if ubuntu-nginx-web-server configurations are still compatible with the new EE release, or if it will be possible to use them.

**Comment by alexlii1971** [comment]
@VirtuBox 

So, any plan to release the new version for EE v4 please?

**Comment by VirtuBox** [comment]
Hello @alexlii1971,

Not yet, it will mostly depend on our usage of EEv4. If we migrate from EEv3 to EEv4, no doubt I will create another repository with EEv4 customization. 
But I'm currently working on https://wordops.org/ (EEv3 Fork) to integrate all my custom configurations to EEv3. It should be (as soon as the first version is released) an up-to-date version of EEv3 and WordOps team already plan to add several new features.
This way, everybody will have the choice between WO (EEv3) or EEv4 depending on their usage or their needs.

**Comment by nsgoyat** [comment]
Great News Master :)
Didn't know you're planning such a great tool. I have been following your work since last 1 Year and I see you are too much dedicated towards the Web performance and a really helping person too.

I have no plans to use EEv4 as of now as EEv3+Your Guides/Configurations are more than enough for me. Can't wait to try my hands on WordOPS. Best of Luck for the project.

**Comment by nsgoyat** [comment]
That's grest Master.
Please, notify through your Twitter handle once you've completed the configurations implementation in WO. I will love to move to WO once you confirm it's ready to replace EEv3.

**Comment by ashishdungdung** [comment]
> Hello @ashishdungdung,
> at the moment I haven't use EEv4 enough to be able to say if ubuntu-nginx-web-server configurations are still compatible with the new EE release, or if it will be possible to use them.

Alright, I would tend to reuse the same configurations by mirroring them on a new server with EE v4.
as the file structure has changed. It will take some to get used to. 

Yes, about WordOps, I have been following that too. Have fired it on several servers, Seems a neat fork.

About using the EEv3 Fork as a tool for managing the servers with up-to-date packages is a bonafide idea. 

About EEv4 it, will take some time for it to mature and people to get experienced with it.

Till then I might as well try to give in some of my findings, some funding, as a contribution to the development.

**Comment by nsgoyat** [comment]
Even I hold myself back from installing WordOPS right now because I see some installation errors reported by users. So as of now, I will just wait for you to publish the information.
Thanks Master :)
