### ISSUE TITLE
Stub Conf

### ISSUE THREAD

**Issue by wiroy** [VirtuBox/ubuntu-nginx-web-server#19]
Hello 

upstream phpstatus {
    server 127.0.0.1:9000
    server unix:/run/php/php7.0-fpm.sock;
    server 127.0.0.1:9070;
    server unix:/run/php70-fpm.sock;
} 

; you have forgotten to put nginx error, please update.

---        server 127.0.0.1:9000;   (;)

**Comment by VirtuBox** [comment]
Hello,
both issues are fixed, thanks for your report
