### ISSUE TITLE
NGINX Configuration failed

### ISSUE THREAD

**Issue by airties1903** [VirtuBox/ubuntu-nginx-web-server#21]
hi

The system crashes when I load NGINX Configuration files. the same way mariadb and MySQL Tuning 

issues : mariadb and mysql tuning " Access denied for user 'root'@'localhost' (using password: YES) "

nginx configuration : nginx -t "nginx: configuration file /etc/nginx/nginx.conf test - [ ] failed"

**Comment by airties1903** [comment]
"ssh connection with ssh keys" : I'm connecting this way but https://github.com/VirtuBox/ee-nginx-setup I get the error when installing 
"the script require to use ssh keys authentification"

can you please tell me how to login and setup

**Comment by VirtuBox** [comment]
Hello @airties1903,
about MariaDB, have you set a password during installation ?

About Nginx, what is the full output of `nginx -t` ?

About ee-nginx-setup, are your ssh keys added in .ssh/authorized_keys ?

**Comment by airties1903** [comment]
about MariaDB, have you set a password during installation ?
"Yeah mariadb asks during installation later asking for security setup"

After installing Easyengine, I'm installing the NGINX Configuration settings that you provided, and the system crashes

Commands:
# copy all common nginx configurations
cp -rf $HOME/ubuntu-nginx-web-server/etc/nginx/conf.d/* /etc/nginx/conf.d/
# commit change with git
git -C /etc/nginx/ add /etc/nginx/ && git -C /etc/nginx/ commit -m "update conf.d configurations"

cp -rf $HOME/ubuntu-nginx-web-server/etc/nginx/common/* /etc/nginx/common/

# commit change with git
git -C /etc/nginx/ add /etc/nginx/ && git -C /etc/nginx/ commit -m "update common configurations"

# TLSv1.2 TLSv1.3 only
cp -f $HOME/ubuntu-nginx-web-server/etc/nginx/nginx.conf /etc/nginx/nginx.conf

# TLS intermediate - TLS v1.0 v1.1 v1.2 v1.3
cp -f $HOME/ubuntu-nginx-web-server/etc/nginx/nginx.conf /etc/nginx/nginx-intermediate.conf

# TLSv1.2 only
cp -f $HOME/ubuntu-nginx-web-server/etc/nginx/nginx.conf /etc/nginx/nginx-tlsv12.conf

# commit change with git
git -C /etc/nginx/ add /etc/nginx/ && git -C /etc/nginx/ commit -m "update nginx.conf configurations"

sudo mkdir -p /etc/systemd/system/nginx.service.d
echo -e '[Service]\nLimitNOFILE=500000' > /etc/systemd/system/nginx.service.d/limits.conf

sudo systemctl daemon-reload
sudo systemctl restart nginx.service




root@vultr:~# nginx -t
nginx: [emerg] unknown directive "fastcgi_socket_keepalive" in /etc/nginx/conf.d/fastcgi.conf:18
nginx: configuration file /etc/nginx/nginx.conf test failed

**Comment by airties1903** [comment]
output
nginx -t 
nginx: [emerg] "aio threads" is unsupported on this platform in /etc/nginx/nginx.conf:63
nginx: configuration file /etc/nginx/nginx.conf test failed

root@vultr:~# service nginx restart
Job for nginx.service failed because the control process exited with error code. See "systemctl status nginx.service" and "journalctl -xe" for details.

**Comment by VirtuBox** [comment]
You have to use my bash script [nginx-ee](https://virtubox.github.io/nginx-ee/) to compile the latest nginx release with additional modules, that's why you currently have issues with `nginx -t`

**Comment by airties1903** [comment]
So how do I do it? I'm having a hard time

6 Ara 2018 Per 13:50 tarihinde VirtuBox <notifications@github.com> şunu
yazdı:

**Comment by airties1903** [comment]
![ekran alintisi](https://user-images.githubusercontent.com/45639040/49595878-1224ba00-f98a-11e8-9823-c6b45ed24558.PNG)

I get the error when I run the "./ee-nginx-setup.sh "command

the script require to use ssh keys authentification

**Comment by nsgoyat** [comment]
@airties1903 You need to run the following bash script:
`bash <(wget -qO - https://raw.githubusercontent.com/VirtuBox/nginx-ee/master/nginx-build.sh)`

**Comment by VirtuBox** [comment]
> I get the error when I run the "./ee-nginx-setup.sh "command
> 
> the script require to use ssh keys authentification

Hello @airties1903, 
You were right, there was an error in the function used to check SSH keys on ee-nginx-setup, I have just pushed the fix on the repository.
But, you are also lucky there was an issue, because you have uploaded your private SSH keys into .ssh/authorized_keys instead of the public one, and in a wrong format. 

An RSA public SSH key look like : 
```bash
ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAQEArm11EMhTPYxj+Ix9oqBYz4Sa9vucQIXUiQjs1YCm7eYMlsaYs/aT7gMVdsh5ZVC0pG27OM9aUzuNWczirb74/+Qtwow7HlGvR5c/yRXAp4qvEChXlbW5SnLXd/DRBojNFojU0tzC5263QgibZeIyIxzr0Su9i9Ejt4oX7Ph/FdFDSHp73mmKi0d9qjuYTbDPerYxuNWz2VoB2hxb+MCHxasCvh2cEvi2j3RtGggDWfEz4ULK/q+6V+HWbkS97FLVE2m9aAtCmsUE5R7A+0ZdJU1BSwBBbCq9VM80le/QRcYdCYRnNpwwaBeWSo/NLvHscbSjWk3FrvsNI9b5MxMHPQ== rsa-key-20181207
```
So delete this key, because you have published a screenshot of the private key, so it's similar to giving your password online. Generate another one, and make sure you have copied the **public** ssh key in .ssh/authorized_keys.

**Comment by airties1903** [comment]
thank you script is working but when nginx.build.sh is installed, openssl fail error :(

**Comment by airties1903** [comment]
![ekran alintisi](https://user-images.githubusercontent.com/45639040/49659179-b07d5200-fa54-11e8-8a34-c7754f562457.PNG)
![ekran alintisi2](https://user-images.githubusercontent.com/45639040/49659181-b07d5200-fa54-11e8-9451-a5cdc59987f7.PNG)

:(

**Comment by VirtuBox** [comment]
Hello @airties1903,
openssl-patch url was changed, fix has been published few minutes ago, you can launch nginx-ee compilation again

**Comment by airties1903** [comment]
#ssl_early_data off; > /etc/nginx/nginx.conf
#fastcgi_socket_keepalive on; > /etc/nginx/conf.d/fastcgi.con

there is also a problem here. very problem that needs to be re-compiled definitely :(

**Comment by VirtuBox** [comment]
Can you give me the output of the command : `nginx -V`

**Comment by airties1903** [comment]
I tried again and the system was successfully installed :) I hope 5-6k moves the visitor instantly
System: 1 CPU, 3.75 GB RAM, 10 GB SSD

**Comment by airties1903** [comment]
oh no the system is running successfully but it does not set up wordpress. but shows that it was set up
