### ISSUE TITLE
Nginx optimized configurations

### ISSUE THREAD

**Issue by juanpvh** [VirtuBox/ubuntu-nginx-web-server#22]
virtualbox, should these settings be used all at once or just one?

# TLSv1.2 TLSv1.3 only
cp -f $HOME/ubuntu-nginx-web-server/etc/nginx/nginx.conf /etc/nginx/nginx.conf

# TLS intermediate - TLS v1.0 v1.1 v1.2 v1.3
cp -f $HOME/ubuntu-nginx-web-server/etc/nginx/nginx.conf /etc/nginx/nginx-intermediate.conf

# TLSv1.2 only
cp -f $HOME/ubuntu-nginx-web-server/etc/nginx/nginx.conf /etc/nginx/nginx-tlsv12.conf

**Comment by VirtuBox** [comment]
Hello @juanpvh,

you should use only one of them, you have the choice depending on your needs.

**Comment by juanpvh** [comment]
@VirtuBox  very thx.
