### ISSUE TITLE
Error connect () to unix: /run/php70-fpm.sock failed (2: No such file or directory)

### ISSUE THREAD

**Issue by raf-rodrigues** [VirtuBox/ubuntu-nginx-web-server#26]
Hi, how are you ?

I used your script to optimize WordOps and it's great I really liked it.
But I'm getting this error in the log.

2019/02/07 06:26:30 [crit] 1706 # 1706: * 795218 connect () to unix: /run/php70-fpm.sock failed (2: No such file or directory) while connecting to upstream, client: Upstream: "fastcgi: // unix: /run/php70-fpm.sock:", host: "127.0.0.1", request: "GET / status? Full & json HTTP / 1.1"

Could you help me understand? Where do I find this error?

Since I thank you and your contribution to this project!

**Comment by VirtuBox** [comment]
Hello @raf-rodrigues,
is php7.0 still installed on your server ? 
Because it seems there is a configuration which set php7.0 upstream to the unix socket /run/php70-fpm.sock but there is no php7.0-fpm pool configuration in the repository, so the unix socket does not exist.
