### ISSUE TITLE
www-two-sock..conf has two dot's

### ISSUE THREAD

**Issue by TheSkyHeart** [VirtuBox/ubuntu-nginx-web-server#27]
Hi,

Thanks a lot for those awesome configuration, it makes everything really fast.

just wanted to give a note about the php pool second socket file it has two dot's in the name
www-two-sock..conf

Thanks

**Comment by VirtuBox** [comment]
Hello @TheSkyHeart,

thanks for your report, issue has been fixed

**Comment by alexlii1971** [comment]
Hello, 

We disable auto update, what might be the issue happen if leave it please?

**Comment by VirtuBox** [comment]
Hello @alexlii1971,

it's not a problem to leave configuration files with the previous name ending with`..conf`, it's only cleaner to have files ending with `.conf`
