### ISSUE TITLE
separate php socket with nginx configs 

### ISSUE THREAD

**Issue by TheSkyHeart** [VirtuBox/ubuntu-nginx-web-server#28]
Hi VirtuBox,

Thanks again for this work, it's helping a lot and making my site load in 2 sec while before doing the configs it was loading in 10 sec.

I tried modifying the files to have a seperate socket and tcp listener for each PHP version, I have also created different php files in /etc/nginx/common so that I can assign each site a different php version, since I still have some sites that need's php 5.6.

so what I did is changed the upstream.conf file to:
`# Common upstream settings

##################
# php5.6-fpm
##################

# TCP/IP on loopback interface
upstream php56-tcp {
server 127.0.0.1:9056;
}

upstream php56 {
least_conn;

server unix:/var/run/php/php56-fpm.sock;
server unix:/var/run/php/php56-two-fpm.sock;

keepalive 5;
}

# Debug Pool
upstream debug {
server 127.0.0.1:9156;
}

##################
# php7.0-fpm
##################

# TCP/IP on loopback interface
upstream php70-tcp {
server 127.0.0.1:9070;
}

# load-balancing on unix socket
upstream php70 {
least_conn;

server unix:/var/run/php/php70-fpm.sock;
server unix:/var/run/php/php70-two-fpm.sock;

keepalive 5;
}

##################
# php7.1-fpm
##################

# TCP/IP on loopback interface
upstream php71-tcp {
server 127.0.0.1:9071;
}

# load-balancing on unix socket
upstream php71 {
least_conn;

server unix:/var/run/php/php71-fpm.sock;
server unix:/var/run/php/php71-two-fpm.sock;

keepalive 5;
}

##################
# php7.2-fpm
##################

# TCP/IP on loopback interface
upstream php72-tcp {
server 127.0.0.1:9072;
}

# load-balancing on unix socket
upstream php72 {
least_conn;

server unix:/var/run/php/php72-fpm.sock;
server unix:/var/run/php/php72-two-fpm.sock;

keepalive 5;
}

##################
# php7.3-fpm
##################

# TCP/IP on loopback interface
upstream php73-tcp {
server 127.0.0.1:9073;
}

# load-balancing on unix socket
upstream php73 {
least_conn;

server unix:/var/run/php/php73-fpm.sock;
server unix:/var/run/php/php73-two-fpm.sock;

keepalive 5;
}

##################
# redis
##################

upstream redis {
    server 127.0.0.1:6379;
    keepalive 10;
}`

and then created a different files for each php version and changed the fastcgi_pass to the socket name.

but when I did that I lost the loading speed for the site and I have no idea that speed it's coming from, I would really appreciate it if we could change those files you have in the repo to give the user the ability to choose what php version needs to use for each site just by editing the site with ee site edit sitename.com
and then change the include to something like this
`server {

    server_name sitename.com   www.sitename.com;

    access_log /var/log/nginx/sitename.com.access.log rt_cache;
    error_log /var/log/nginx/sitename.com.error.log;

    root /var/www/sitename.com/htdocs;

    index index.php index.html index.htm;

    include common/php73.conf;

    include common/wpcommon-php73.conf;
    include common/locations-php73.conf;
    include /var/www/sitename.com/conf/nginx/*.conf;
}`

thanks again.

**Comment by TheSkyHeart** [comment]
Hi again,

I'm still not able to figure out where the speed is coming from, by just doing those few command:
```
# php7.3-fpm
apt update && apt install php7.3-fpm php7.3-xml php7.3-bz2 php7.3-zip php7.3-mysql php7.3-intl php7.3-gd php7.3-curl php7.3-soap php7.3-mbstring php7.3-bcmath -y

# copy php-fpm pools & php.ini configuration
cp -rf $HOME/ubuntu-nginx-web-server/etc/php/7.3/fpm/* /etc/php/7.3/fpm/
cp -rf $HOME/ubuntu-nginx-web-server/etc/php/7.3/cli/* /etc/php/7.3/cli/
service php7.3-fpm restart

git -C /etc/php/ add /etc/php/ && git -C /etc/php/ commit -m "add php7.3 configuration"
```

```
# copy all common nginx configurations
cp -rf $HOME/ubuntu-nginx-web-server/etc/nginx/conf.d/* /etc/nginx/conf.d/

# commit change with git
git -C /etc/nginx/ add /etc/nginx/ && git -C /etc/nginx/ commit -m "update conf.d configurations"
```

```
cp -rf $HOME/ubuntu-nginx-web-server/etc/nginx/common/* /etc/nginx/common/

# commit change with git
git -C /etc/nginx/ add /etc/nginx/ && git -C /etc/nginx/ commit -m "update common configurations"
```

is this file wp-fcgi-cache-php72.conf somehow included by default some where in the configs?
I can get the site loading faster if include that file with the vhost configs and replacing it with php73.conf

```
server_name sitename.com   www.sitename.com;


access_log /var/log/nginx/sitename.com.access.log rt_cache;
error_log /var/log/nginx/sitename.com.error.log;


root /var/www/sitename.com/htdocs;



index index.php index.html index.htm;


include common/wp-fcgi-cache-php72.conf;

include common/wpcommon-php73.conf;
include common/locations-php73.conf;
include /var/www/sitename.com/conf/nginx/*.conf;
```

thanks in advance.

**Comment by VirtuBox** [comment]
Hello @TheSkyHeart,

If you have only add php upstreams for php5.6 and php7.0, it should not make an huge difference with the previous configuration.  Have you use a similar php.ini and the same php-fpm pools configuration ?
Otherwise, including my fastcgi_cache configuration is a good way to speed-up your website, it only require to preload cache to make sure pages are directly served from nginx cache.
