### ISSUE TITLE
wpcommon-php71.conf and wpcommon-php72.conf are crossed

### ISSUE THREAD

**Issue by lpienia** [VirtuBox/ubuntu-nginx-web-server#3]
This two files are crossed. Look at the php cgi version of each one.

# php7.1
https://raw.githubusercontent.com/VirtuBox/ubuntu-nginx-web-server/master/etc/nginx/common/wpcommon-php71.conf -> Pointed to   fastcgi_pass php72;

# php7.2
https://raw.githubusercontent.com/VirtuBox/ubuntu-nginx-web-server/master/etc/nginx/common/wpcommon-php72.conf-> Pointed to   fastcgi_pass php71;

**Comment by VirtuBox** [comment]
Thanks for the report. It's now fixed
