### ISSUE TITLE
Git fatal error

### ISSUE THREAD

**Issue by wiroy** [VirtuBox/ubuntu-nginx-web-server#31]
git -C /etc/nginx/ add /etc/nginx/ && git -C /etc/nginx/ commit -m "update common configurations" fatal: not a git repository (or any of the parent directories): .git

new error update

Mar 22 15:00:18 firewall fail2ban-server[25883]:  No file(s) found for glob /var/log/nginx/*access.log
Mar 22 15:00:18 firewall fail2ban-server[25883]:  Failed during configuration: Have not found any log file for ee-wordpre

**Comment by famfam** [comment]
Same here.

**Comment by VirtuBox** [comment]
Hello,

I have updated the documentation and also added warning message on section than may not be needed anymore with WordOps. Please visit the github page to see this warning in red color : https://virtubox.github.io/ubuntu-nginx-web-server/
