### ISSUE TITLE
Error with Nginx optimized configurations

### ISSUE THREAD

**Issue by famfam** [VirtuBox/ubuntu-nginx-web-server#32]
# commit change with git
git -C /etc/nginx/ add . && git -C /etc/nginx/ commit -m "update nginx.conf configurations"

fatal: not a git repository (or any of the parent directories): .git

**Comment by VirtuBox** [comment]
Issue has been fixed with commit https://github.com/VirtuBox/ubuntu-nginx-web-server/commit/f283edd7020ccab1a78c4ce140a9096753e5f4f0
