### ISSUE TITLE
-bash: /etc/bash_completion.d/wo_auto.rc: No such file or directory

### ISSUE THREAD

**Issue by jeka6774** [VirtuBox/ubuntu-nginx-web-server#36]
Hi.
# noninteractive install - you can replace $USER with your username & root@$HOSTNAME by your email
sudo bash -c 'echo -e "[user]\n\tname = $USER\n\temail = root@$HOSTNAME" > $HOME/.gitconfig'

wget -qO wo wordops.se/tup && sudo bash wo

this error appears

-bash: /etc/bash_completion.d/wo_auto.rc: No such file or directory

**Comment by VirtuBox** [comment]
Hello,

Install command was updated since several months : 

```bash
wget -qO wo wops.cc && sudo bash wo
```
