### ISSUE TITLE
wpcommon-php73.conf has errors

### ISSUE THREAD

**Issue by demyxco** [VirtuBox/ubuntu-nginx-web-server#38]
It looks incomplete and rushed, not properly formatted either.

https://github.com/VirtuBox/ubuntu-nginx-web-server/blob/bc249cbc48aa8f9292bb63238c2884c55537858c/etc/nginx/common/wpcommon-php73.conf#L45-L81

**Comment by VirtuBox** [comment]
Hello @demyxco,
thanks for your report, it was a mistake and it's fixed now.
