### ISSUE TITLE
Nginx Pagespeed caching issue

### ISSUE THREAD

**Issue by w33zy** [VirtuBox/ubuntu-nginx-web-server#7]
Did you guys figure out a workaround, fix or solution for the issue discussed here?

https://github.com/EasyEngine/easyengine/issues/497

**Comment by VirtuBox** [comment]
Hello @w33zy, 

I'm not sure to understand the issue you had with pagespeed. If it's about resources usage during load testing with ngx_pagespeed, there is no issue.
With pagespeed enabled, you will not be able to handle the same traffic than without pagespeed. 

But replacing memcached by redis is a good solution to improve performances with pagespeed.

**Comment by w33zy** [comment]
What I am trying to get at is if you came across the same technical issues that caused the EE team to remove Pagespeed support from `ee`

**Comment by VirtuBox** [comment]
No, I have only few servers running with ngx_pagespeed and no technical issues.
But pagespeed module is only required when you use another cms than WP, without the ability to optimize images and static assets (in my case, I use pagespeed for my ghost blogs).

**Comment by w33zy** [comment]
OK. I was looking to make use of the auto-inlining CSS/JS feature. I will run my own tests and see if it holds up.
