### ISSUE TITLE
MySQL with VPS 2 GB ram

### ISSUE THREAD

**Issue by jonathannz** [VirtuBox/ubuntu-nginx-web-server#8]
Hi there,
First up, this has to be one of the most helpful and flawless set of server set up instructions I've come across. I got started with the standard EE installation, but felt like a lot of things where missing, out of date, or overlooked.
Stumbling across your instructions has resolved that, more than I could have hoped for.

I have a question re your mysql cnf file (https://github.com/VirtuBox/ubuntu-nginx-web-server/blob/master/etc/mysql/my.cnf)

You say it's been optimised for a VPS with 4 GB of RAM.

Are you able to suggest what changes to make to it for a VPS with 2 GB of RAM?

Thanks very much,

Jonathan

**Comment by VirtuBox** [comment]
Hello @jonathannz , the most important variables to changes are : 
```
myisam_sort_buffer_size	= 256M
---
innodb_log_file_size	= 128M
innodb_buffer_pool_size	= 1G
innodb_log_buffer_size	= 256M
```

**Comment by jonathannz** [comment]
Thanks very much. Without your excellent configuration info I was going to abandon trying to switch to EE, and revert to setting up my VPS manually. I am glad I stumbled across your posts.
